## Import Lib

In [2]:
import pickle
import pandas as pd
import numpy as np
import sklearn

# Demo RandomForest - `Penentuan Harga Pasar`

## Import Data Regression

In [48]:
data_reg = pd.read_csv('Data/DC_Prop_Residential_Regression_DEMO1.csv', index_col= 'Unnamed: 0')

# Set Index
indeks = pd.Series(range(data_reg.shape[0]))
data_reg = data_reg.set_index([indeks])

data_reg_RF = data_reg.drop(['ID_PROP', 'PRICE'], axis =1)

In [49]:
data_reg_RF.head()

,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,SALE_NUM,...,INTWALL_Vinyl Comp,INTWALL_Vinyl Sheet,INTWALL_Wood Floor,WARD_Ward 2,WARD_Ward 3,WARD_Ward 4,WARD_Ward 5,WARD_Ward 6,WARD_Ward 7,WARD_Ward 8
0,4,0,2.0,8,4,1910.0,1988.0,1972,3.0,1,...,0,0,0,1,0,0,0,0,0,0
1,3,1,2.0,9,5,1910.0,2009.0,1984,3.0,3,...,0,0,0,1,0,0,0,0,0,0
2,3,1,2.0,8,5,1900.0,2003.0,1984,3.0,1,...,0,0,0,1,0,0,0,0,0,0
3,3,1,2.0,8,4,1906.0,2011.0,1972,3.0,1,...,0,0,0,1,0,0,0,0,0,0
4,3,1,2.0,7,3,1908.0,2008.0,1967,2.0,4,...,0,0,0,1,0,0,0,0,0,0

In [50]:
model_RF = 'model_randomForest_r_undrop.sav'
loaded_model_RF = pickle.load(open(model_RF, 'rb'))

In [51]:
predict_RF= pd.DataFrame(loaded_model_RF.predict(data_reg_RF))
predict_RF.columns = ['PREDICT_PRICE']
predict_RF['PREDICT_PRICE'] = predict_RF['PREDICT_PRICE']**3
predict_RF

       PREDICT_PRICE
0       1.025779e+06
1       1.981904e+06
2       1.417948e+06
3       1.112525e+06
4       1.369451e+06
...              ...
45846   1.123915e+05
45847   1.834933e+05
45848   1.114651e+05
45849   2.055122e+05
45850   1.654535e+05

[45851 rows x 1 columns]

In [52]:
cols = data_reg.columns.to_list() + predict_RF.columns.to_list()
dfs = [data_reg,predict_RF]
result = np.concatenate(dfs, axis=1)  
result = pd.DataFrame(result, columns=cols)
result.head()

,ID_PROP,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,INTWALL_Vinyl Sheet,INTWALL_Wood Floor,WARD_Ward 2,WARD_Ward 3,WARD_Ward 4,WARD_Ward 5,WARD_Ward 6,WARD_Ward 7,WARD_Ward 8,PREDICT_PRICE
0,0.0,4.0,0.0,2.0,8.0,4.0,1910.0,1988.0,1972.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.025779e+06
1,2.0,3.0,1.0,2.0,9.0,5.0,1910.0,2009.0,1984.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.981904e+06
2,3.0,3.0,1.0,2.0,8.0,5.0,1900.0,2003.0,1984.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.417948e+06
3,7.0,3.0,1.0,2.0,8.0,4.0,1906.0,2011.0,1972.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.112525e+06
4,8.0,3.0,1.0,2.0,7.0,3.0,1908.0,2008.0,1967.0,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.369451e+06

# Demo KMEANS - `Penentuan Resiko`

## Import data Clustering

In [56]:
# Loading the dataset
data_clus = pd.read_csv('Data/DC_Prop_Residential_Clustering_DEMO1.csv', index_col='Unnamed: 0')

In [57]:
data_clus.shape

(57798, 31)

In [59]:
# Set Index
indeks = pd.Series(range(data_clus.shape[0]))
data_clus = data_clus.set_index([indeks])

# Sampling
data_clus_KM = data_clus.drop(['ID_PROP'], axis =1)

In [60]:
model_KM = 'model_Clus_Kmeans_r.sav'
loaded_model_KM = pickle.load(open(model_KM, 'rb'))

In [61]:
predict_KM= pd.DataFrame(loaded_model_KM.predict(data_clus_KM))
predict_KM.columns = ['PREDICT_CLUSTER']
predict_KM.shape

C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KMeans was fitted without feature names
  warnings.warn(

(57798, 1)

In [62]:
cols = data_clus.columns.to_list() + predict_KM.columns.to_list()
dfs = [data_clus,predict_KM]
result_data_clus = np.concatenate(dfs, axis=1)  
result_data_clus = pd.DataFrame(result_data_clus, columns=cols)
result_data_clus.shape

(57798, 32)

In [63]:
result_data_clus['RISK'] = np.where(result_data_clus['PREDICT_CLUSTER'] == 0, 0.8, 
                    (np.where(result_data_clus['PREDICT_CLUSTER'] == 1, 0.5, 0.7)))

In [64]:
result_data_clus

,ID_PROP,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,INTWALL,KITCHENS,FIREPLACES,USECODE,LANDAREA,WARD,SalevYB,SalevYI,PREDICT_CLUSTER,RISK
0,0.0,4.0,0.0,0.0,1.0,2.0,8.0,4.0,1910.0,1988.0,...,0.0,2.0,5.0,24.0,1680.0,1.0,93.0,31.0,0.0,0.8
1,2.0,3.0,1.0,1.0,1.0,2.0,9.0,5.0,1910.0,2009.0,...,0.0,2.0,4.0,24.0,1680.0,1.0,106.0,32.0,0.0,0.8
2,3.0,3.0,1.0,1.0,1.0,2.0,8.0,5.0,1900.0,2003.0,...,0.0,2.0,3.0,24.0,1680.0,1.0,106.0,22.0,0.0,0.8
3,5.0,3.0,2.0,1.0,1.0,1.0,10.0,5.0,1913.0,1972.0,...,0.0,1.0,4.0,11.0,2196.0,1.0,97.0,38.0,0.0,0.8
4,7.0,3.0,1.0,1.0,1.0,2.0,8.0,4.0,1906.0,2011.0,...,0.0,2.0,1.0,24.0,1627.0,1.0,105.0,39.0,0.0,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57793,106687.0,2.0,0.0,2.0,0.0,2.0,10.0,4.0,1953.0,1962.0,...,2.0,2.0,0.0,23.0,5837.0,7.0,51.0,42.0,1.0,0.5
57794,106688.0,2.0,0.0,2.0,1.0,2.0,10.0,4.0,1953.0,2017.0,...,0.0,2.0,0.0,23.0,5302.0,7.0,63.0,45.0,1.0,0.5
57795,106692.0,2.0,0.0,2.0,0.0,2.0,10.0,5.0,1953.0,1962.0,...,0.0,2.0,0.0,23.0,5348.0,7.0,59.0,50.0,1.0,0.5
57796,106694.0,2.0,0.0,2.0,0.0,2.0,10.0,4.0,1953.0,2017.0,...,0.0,2.0,0.0,23.0,3046.0,7.0,64.0,46.0,1.0,0.5
57797,106695.0,2.0,0.0,2.0,1.0,2.0,10.0,4.0,1953.0,2018.0,...,0.0,2.0,0.0,23.0,5098.0,7.0,64.0,46.0,1.0,0.5

In [65]:
cluster_result_only = result_data_clus[['ID_PROP', 'PREDICT_CLUSTER',	'RISK']]

In [77]:
result = result.set_index('ID_PROP').join(cluster_result_only.set_index('ID_PROP'))

## PREDIKSI HARGA BELI

In [78]:
result['HARGA_BELI']=result['PREDICT_PRICE']*result['RISK']
result

C:\Users\user\AppData\Local\Temp\ipykernel_22136\1854616086.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result['HARGA_BELI']=result['PREDICT_PRICE']*result['RISK']

,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,PRICE,...,WARD_Ward 3,WARD_Ward 4,WARD_Ward 5,WARD_Ward 6,WARD_Ward 7,WARD_Ward 8,PREDICT_PRICE,PREDICT_CLUSTER,RISK,HARGA_BELI
ID_PROP,,,,,,,,,,,,,,,,,,,,,
0.0,4.0,0.0,2.0,8.0,4.0,1910.0,1988.0,1972.0,3.0,103.071368,...,0.0,0.0,0.0,0.0,0.0,0.0,1.025779e+06,0.0,0.8,8.206228e+05
2.0,3.0,1.0,2.0,9.0,5.0,1910.0,2009.0,1984.0,3.0,128.057916,...,0.0,0.0,0.0,0.0,0.0,0.0,1.981904e+06,0.0,0.8,1.585523e+06
3.0,3.0,1.0,2.0,8.0,5.0,1900.0,2003.0,1984.0,3.0,117.009423,...,0.0,0.0,0.0,0.0,0.0,0.0,1.417948e+06,0.0,0.8,1.134358e+06
7.0,3.0,1.0,2.0,8.0,4.0,1906.0,2011.0,1972.0,3.0,101.639636,...,0.0,0.0,0.0,0.0,0.0,0.0,1.112525e+06,0.0,0.8,8.900200e+05
8.0,3.0,1.0,2.0,7.0,3.0,1908.0,2008.0,1967.0,2.0,112.662317,...,0.0,0.0,0.0,0.0,0.0,0.0,1.369451e+06,0.0,0.8,1.095561e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106687.0,2.0,0.0,2.0,10.0,4.0,1953.0,1962.0,1962.0,2.0,45.629026,...,0.0,0.0,0.0,0.0,0.0,1.0,1.123915e+05,1.0,0.5,5.619573e+04
106688.0,2.0,0.0,2.0,10.0,4.0,1953.0,2017.0,1971.0,2.0,56.980192,...,0.0,0.0,0.0,0.0,0.0,1.0,1.834933e+05,1.0,0.5,9.174664e+04
106692.0,2.0,0.0,2.0,10.0,5.0,1953.0,1962.0,1962.0,2.0,46.415888,...,0.0,0.0,0.0,0.0,0.0,1.0,1.114651e+05,1.0,0.5,5.573254e+04
106694.0,2.0,0.0,2.0,10.0,4.0,1953.0,2017.0,1971.0,2.0,59.907264,...,0.0,0.0,0.0,0.0,0.0,1.0,2.055122e+05,1.0,0.5,1.027561e+05
106695.0,2.0,0.0,2.0,10.0,4.0,1953.0,2018.0,1971.0,2.0,51.924941,...,0.0,0.0,0.0,0.0,0.0,1.0,1.654535e+05,1.0,0.5,8.272674e+04

## DEMO TIME SERIES - `Prediksi Tren Kenaikan Harga`

In [79]:
tren_res = 0.0681
tren_con = 0.1643

result['TREND'] = tren_res

C:\Users\user\AppData\Local\Temp\ipykernel_22136\1965824790.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result['TREND'] = tren_res

## Prediksi Harga Jual

In [82]:
result['HARGA_JUAL'] = result['PREDICT_PRICE'] * (1+result['TREND'])
result['PROFIT'] = result['HARGA_JUAL'] - result['PREDICT_PRICE']

AYH = result[[ 'PREDICT_PRICE',	'PREDICT_CLUSTER',	'RISK',	'HARGA_BELI', 'TREND', 'HARGA_JUAL', 'PROFIT']]
AYH

,PREDICT_PRICE,PREDICT_CLUSTER,RISK,HARGA_BELI,TREND,HARGA_JUAL,PROFIT
ID_PROP,,,,,,,
0.0,1.025779e+06,0.0,0.8,8.206228e+05,0.0681,1.095634e+06,69855.516152
2.0,1.981904e+06,0.0,0.8,1.585523e+06,0.0681,2.116871e+06,134967.630037
3.0,1.417948e+06,0.0,0.8,1.134358e+06,0.0681,1.514510e+06,96562.232882
7.0,1.112525e+06,0.0,0.8,8.900200e+05,0.0681,1.188288e+06,75762.955927
8.0,1.369451e+06,0.0,0.8,1.095561e+06,0.0681,1.462711e+06,93259.633120
...,...,...,...,...,...,...,...
106687.0,1.123915e+05,1.0,0.5,5.619573e+04,0.0681,1.200453e+05,7653.858386
106688.0,1.834933e+05,1.0,0.5,9.174664e+04,0.0681,1.959892e+05,12495.892015
106692.0,1.114651e+05,1.0,0.5,5.573254e+04,0.0681,1.190559e+05,7590.772215
106694.0,2.055122e+05,1.0,0.5,1.027561e+05,0.0681,2.195076e+05,13995.381696
106695.0,1.654535e+05,1.0,0.5,8.272674e+04,0.0681,1.767209e+05,11267.382322